version: "3.3"

services:

  central-collector:
    #image: opensciencegrid/ce-collector
    build: .
    volumes:
      # apache
      - ./etc/httpd/conf.d/htcondorce_registry.conf:/etc/httpd/conf.d/htcondorce_registry.conf:ro
      # grid-security
      - ./certs/tls.crt:/certs/tls.crt:ro
      - ./certs/tls.key:/certs/tls.key:ro
    ports:
      - "8080:80"
      - "8443:443"
